ゲストユーザーログイン機能とヘッダーの作成完了
YukiIshizaki0525/tenkue-board-r019 pull request #3
Opened 2021-03-01 15:30 UTC by YukiIshizaki0525

◎deviseメッセージを日本語化するため 'devise-i18n', 'devise-i18n-views' Gemを追加。
トップページを仮で作成(homes#index)
・HomesControllerを作成
・valiable.scssをmoduleフォルダに追加。

◎ApplicationControllerに関する変更内容

CSRF対策
ログイン済みユーザーのみアクセス許可
deviseコントローラーにストロングパラメータを追加
新規登録時のストロングパラメータを作成
・headerに関する変更内容

sharedフォルダを作成し、_header.html.erbをtempleteフォルダからsharedフォルダに移動
ログイン状態によってヘッダーの表示内容を変更
ログイン中のユーザー名がヘッダーに表示される仕様にしました。
ヘッダーの項目をリンク化
フラッシュに関する変更内容

layoutsフォルダにnotifications.html.erbを追加。
notification.scssを作成し、フラッシュに関するスタイルを追加。
「ログアウトしました」というフラッシュメッセージが表示できない問題については別ブランチにて改善予定

2021-03-03 03:36 UTC, sew-sou19 requested changes
コミットは細かく分けましょう！
1コミットに一意が理想です。

また、プルリクには変更分のみが確認できる状態が理想です。（そうでないとどこを変更して、どこをレビューすべきかが分からないので）

`Files Changed`が495あるのは普通にびっくりします笑
変更分のみが表示されるようにしましょう！
（おそらくbaseブランチの向き先の問題かなと）

2021-03-03 11:43 UTC, sew-sou19 requested changes
コメントしました。
ご確認と修正お願いしますー！

2021-03-03 11:43 UTC, sew-sou19 commented on app/assets/javascripts/homes.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
今回はcoffeeファイルは使用しないかと思います。
混乱を防ぐためにも不要なファイルは削除しましょうー！

2021-03-03 11:43 UTC, sew-sou19 commented on app/assets/stylesheets/application.scss
> +// @import "bootstrap/scss/bootstrap";
不要な記述はコメントアウトではなく削除しましょうー！

2021-03-03 11:43 UTC, sew-sou19 commented on app/views/layouts/_notifications.html.erb
> +<!-- alertかnoticeで切り分けされます -->
コメントは、どうしてもの時以外は極力使用しないようにしましょうー！
コードを見るだけで理解できるように記述するのが理想です。

2021-03-03 11:43 UTC, sew-sou19 commented on app/views/shared/_header.html.erb
> +      <%# ルートパスへのリンクを設置 %>
不要なコメントは（予め設置されていたものも）削除しましょうー！

2021-03-03 11:43 UTC, sew-sou19 commented on vendor/bundle/ruby/2.5.0/extensions/x86_64-darwin-19/2.5.0/bcrypt-3.1.15/gem_make.out
>  current directory: /Users/yuki.ishizaki/tenkue-board-r019/vendor/bundle/ruby/2.5.0/gems/bcrypt-3.1.15/ext/mri
`vendor/bundle/ruby/2.5.0/extensions/x86_64-darwin-19/2.5.0/bcrypt-3.1.15/gem_make.out`などの不要なファイルが大量に存在・変更されているので、ここ解消できるといいかと思いますー！

おそらく他の方の環境にはこのファイル存在しないので、コンフリクトやおかしな動作に影響してくるかもです

git管理する必要がなければ、gitignoreに記述するのがいいかと思います。

2021-03-04 09:35 UTC, YukiIshizaki0525 commented on app/assets/javascripts/homes.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
ご指摘ありがとうございます。
削除いたしました。

2021-03-04 09:36 UTC, YukiIshizaki0525 commented on app/assets/stylesheets/application.scss
> +// @import "bootstrap/scss/bootstrap";
ご指摘ありがとうございます。
削除いたしました。

2021-03-04 09:38 UTC, YukiIshizaki0525 commented on app/views/layouts/_notifications.html.erb
> +<!-- alertかnoticeで切り分けされます -->
ご指摘いただきましてありがとうございます。
削除いたしました。

2021-03-04 09:39 UTC, YukiIshizaki0525 commented on app/views/shared/_header.html.erb
> +      <%# ルートパスへのリンクを設置 %>
ご指摘いただきましてありがとうございます。
削除いたしました。

2021-03-04 09:42 UTC, YukiIshizaki0525 commented on vendor/bundle/ruby/2.5.0/extensions/x86_64-darwin-19/2.5.0/bcrypt-3.1.15/gem_make.out
>  current directory: /Users/yuki.ishizaki/tenkue-board-r019/vendor/bundle/ruby/2.5.0/gems/bcrypt-3.1.15/ext/mri
vendor/bundleはgit管理不要だということを失念しておりました。
gitignoreに追加しました。

2021-03-04 11:18 UTC, sew-sou19 reviewed
`Files changed`の数はチェックしましょうー！
ここがカンストするのは、何かがおかしいと思った方がいいです。

gitignoreに追加してるのにvendor/bundleがまだgit管理対象になってるので、確認しましょう。

繰り返しになりますが、プルリクには正しい変更分のみを確認できるようにしてください。
もし埒があかない場合はブランチを切り直してください。

2021-03-08 10:12 UTC, closed without merging