掲示板新規登録機能の実装が完了いたしました。
YukiIshizaki0525/tenkue-board-r019 pull request #7
Opened 2021-03-08 10:12 UTC by YukiIshizaki0525

■変更点
・投稿内容はcontentというカラムで管理
・未入力で登録不可
・投稿内容は140字以内
・_error_messages.html.erbをtemplateフォルダからsharedフォルダに移動
・投稿時のフラッシュメッセージを設定
・エラーメッセージ追加のため、rails-i18n Gemの追加
・ja.ymlを作成し、contentを「投稿内容」としてエラーメッセージの際、日本語化するようにしました。
・投稿内容に不備がある場合は、登録フォームにリダイレクトし、入力した内容が残っている仕様にしました。
・未ログインの状態で投稿フォームのパスを入力しても、トップページに戻され、「ログインまたは新規登録が必要です」というフラッシュメッセージが表示される仕様にしました。

2021-03-09 12:38 UTC, sew-sou19 commented
繰り返しになりますが、コミットは細かく分けましょうー！
1コミット=1つの意味、にするのが理想です。

またコミットメッセージは何をしたか書いておくとレビュワーが見やすいです！

2021-03-09 12:50 UTC, sew-sou19 requested changes
レビュー完了しました
ご確認＆修正お願いしますー！

2021-03-09 12:50 UTC, sew-sou19 commented on app/controllers/boards_controller.rb
> +    if user_signed_in?
deviseを使用してるので、`authenticate_user!`の記述で対応しましょう！

2021-03-09 12:50 UTC, sew-sou19 commented on app/controllers/boards_controller.rb
> +      redirect_to new_board_path, flash: {
redirectではなくrenderを使用しましょう！

2021-03-09 12:50 UTC, sew-sou19 commented on app/models/board.rb
> +  validates :content, presence: true, length: { maximum: 140 }
userモデルとのアソシエーションを記述しましょう！

2021-03-09 12:50 UTC, sew-sou19 commented on app/controllers/boards_controller.rb
> +      params.require(:board).permit(:content)
これだとUserとBoardが紐づいていないので、修正しましょう！

2021-03-09 12:50 UTC, sew-sou19 commented on db/migrate/20210307095420_create_boards.rb
> +
usersテーブルへの外部キーを追加しましょう！

2021-03-13 04:13 UTC, YukiIshizaki0525 commented on app/controllers/boards_controller.rb
> +    if user_signed_in?
修正いたしました。

2021-03-13 04:13 UTC, YukiIshizaki0525 commented on app/models/board.rb
> +  validates :content, presence: true, length: { maximum: 140 }
修正いたしました。

2021-03-13 04:16 UTC, YukiIshizaki0525 commented on app/controllers/boards_controller.rb
> +      params.require(:board).permit(:content)
修正しました。

2021-03-14 17:13 UTC, sew-sou19 approved these changes
レビュー期限過ぎてるのでApproveしてしまいますー！
修正したらそのままマージしてください。

2021-03-14 17:13 UTC, sew-sou19 commented on app/controllers/boards_controller.rb
> +      render :new
投稿に成功した場合にnewにrenderさせてしまうと投稿した内容が確認できずユーザビリティが落ちるので、showかindexにredirectさせてあげるのがいいと思いますー！

2021-03-14 17:13 UTC, sew-sou19 commented on app/controllers/boards_controller.rb
> +      params.permit(:content, :user_id)
requireなくてcontent取れてますかね、、、？取れてるなら問題ないですー！

2021-03-14 17:13 UTC, sew-sou19 commented on app/controllers/boards_controller.rb
> +    board = current_user.boards.new(board_params)
hidden_fieldでuser_idをpostしてるならcurrent_userはなくてもいいですね。
どちらかでいいです。

2021-03-19 00:08 UTC, merged